name: R-CMD-check-bioc

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:
  R-CMD-check-bioc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: 'devel', bioc: 'devel' }
          - { r: 'release', bioc: 'release' }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Setup Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc }}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'

      - name: BiocCheck
        run: |
          BiocManager::install("BiocCheck")
          BiocCheck::BiocCheck(".")
        shell: Rscript {0}
